---
version: "3"
services:
 devopsdb:
   image: prasadrao1122/mynewrepo:dbimage
   ports:
     - "3306:3306"

 application:
   image: prasadrao1122/mynewrepo:appimage
   ports:
     - "1122:8080"
   depends_on:
     - "devopsdb"
